dist: trusty

language: php

services:
    - mysql
    - postgresql

# Mysql isn't installed on trusty (only client is), so we need to specifically install it
addons:
    apt:
        packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        -   name: '[PHP 7.1] Unit tests with ezpublish-kernel:^7.5.1@dev'
            php: '7.1'
            env: SCRIPT="php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c phpunit.xml" COMPOSER_REQUIRE="ezsystems/ezpublish-kernel:^7.5.1@dev"
        -   name: '[PHP 7.1] Legacy SQLite database integration tests with ezpublish-kernel:^7.5.1@dev'
            php: '7.1'
            env: SCRIPT="php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c phpunit-integration-legacy.xml" COMPOSER_REQUIRE="ezsystems/ezpublish-kernel:^7.5.1@dev"
        -   name: '[PHP 7.1] Solr 6.6.0 integration tests with ezpublish-kernel:^7.5.1@dev'
            php: '7.1'
            env: SCRIPT="php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c phpunit-integration-legacy-solr.xml" SOLR_VERSION="6.6.0" CORES_SETUP="shared" SOLR_CONFIG="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml" COMPOSER_REQUIRE="ezsystems/ezpublish-kernel:^7.5.1@dev"
        -   name: '[PHP 7.1] Empty PostgreSQL Legacy database integration tests with ezpublish-kernel:^7.5.1@dev'
            php: '7.1'
            env: SCRIPT="php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c phpunit-integration-legacy-empty-db.xml" DB="postgresql" DATABASE="pgsql://postgres@localhost/testdb" COMPOSER_REQUIRE="ezsystems/ezpublish-kernel:^7.5.1@dev"
        -   name: '[PHP 7.1] Empty MySQL Legacy database integration tests with ezpublish-kernel:^7.5.1@dev'
            php: '7.1'
            env: SCRIPT="php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c phpunit-integration-legacy-empty-db.xml" DB="mysql" DATABASE="mysql://root@localhost/testdb" COMPOSER_REQUIRE="ezsystems/ezpublish-kernel:^7.5.1@dev"
        -   name: '[PHP 7.1] Unit tests with ezpublish-kernel:^6.13.6@dev'
            php: '7.1'
            env: SCRIPT="php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c phpunit.xml" COMPOSER_REQUIRE="ezsystems/ezpublish-kernel:^6.13.6@dev"
        -   name: '[PHP 5.6] Unit tests'
            php: '5.6'
            env: SCRIPT="php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c phpunit.xml"
        -   name: '[PHP 5.6] Solr 4.10.4 integration tests'
            php: '5.6'
            env: SCRIPT="php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c phpunit-integration-legacy-solr.xml" SOLR_VERSION="4.10.4" CORES_SETUP="single" SOLR_CORES="collection1" SOLR_CONFIG="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml"
        -   name: '[PHP 7.3] Code Style Validation'
            php: '7.2'
            env: SCRIPT="./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating"

# test only master (+ Pull requests)
branches:
    only:
        - master


# setup requirements for running db tests
before_install:
    - ./bin/.travis/prepare_unittest.sh

before_script:
    # Disable memory_limit for composer
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install --no-progress --no-interaction --prefer-dist
    - if [ "$SOLR_VERSION" != "" ] ; then ./vendor/ezsystems/ezplatform-solr-search-engine/bin/.travis/init_solr.sh ; fi

script:
    - echo "${SCRIPT}" && ${SCRIPT}

notifications:
    email: false

# reduce depth (history) of git checkout
git:
    depth: 30
