services:
    ezxmltext.command.gateway.richtext_converter:
        class: EzSystems\EzPlatformXmlTextFieldTypeBundle\Command\Gateway\RichTextConverterGateway
        arguments:
            - '@ezpublish.persistence.connection'
